Args = -H:+UnlockExperimentalVMOptions \
       -H:+SharedArenaSupport \
       -H:-UnlockExperimentalVMOptions \
       --features=io.github.kdroidfilter.composemediaplayer.mpv.internal.MpvNativeImageFeature
