[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $OutputRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$VcpkgCommit = "baddcee32f29086c2c1c1f002df5078e371f7934"
$LibAssVersion = "0.17.4"
$ModuleDirectory = (Resolve-Path (Join-Path $PSScriptRoot "../..")).Path
$BuildRoot = if ($env:KMEDIA_ASS_DESKTOP_BUILD_ROOT) {
    [IO.Path]::GetFullPath($env:KMEDIA_ASS_DESKTOP_BUILD_ROOT)
} else {
    Join-Path $ModuleDirectory "build/desktop-ass-native"
}
$VcpkgRoot = Join-Path $BuildRoot "vcpkg-$VcpkgCommit"
$InstalledRoot = Join-Path $BuildRoot "vcpkg-installed"
$ResolvedOutputRoot = [IO.Path]::GetFullPath($OutputRoot)

New-Item -ItemType Directory -Force -Path $BuildRoot, $ResolvedOutputRoot | Out-Null

if (-not (Test-Path -LiteralPath (Join-Path $VcpkgRoot ".git"))) {
    git clone --filter=blob:none --no-checkout https://github.com/microsoft/vcpkg.git $VcpkgRoot
    if ($LASTEXITCODE -ne 0) {
        throw "Could not clone the pinned vcpkg repository."
    }
}

git -C $VcpkgRoot fetch --depth 1 origin $VcpkgCommit
if ($LASTEXITCODE -ne 0) {
    throw "Could not fetch pinned vcpkg commit $VcpkgCommit."
}
git -C $VcpkgRoot checkout --detach $VcpkgCommit
if ($LASTEXITCODE -ne 0) {
    throw "Could not check out pinned vcpkg commit $VcpkgCommit."
}
$ActualCommit = (git -C $VcpkgRoot rev-parse HEAD).Trim()
if ($ActualCommit -ne $VcpkgCommit) {
    throw "Pinned vcpkg checkout mismatch: expected $VcpkgCommit, got $ActualCommit."
}

$VcpkgExecutable = Join-Path $VcpkgRoot "vcpkg.exe"
if (-not (Test-Path -LiteralPath $VcpkgExecutable)) {
    & (Join-Path $VcpkgRoot "bootstrap-vcpkg.bat") -disableMetrics
    if ($LASTEXITCODE -ne 0) {
        throw "Could not bootstrap pinned vcpkg."
    }
}

$Triplets = @(
    [PSCustomObject]@{ Name = "x64-windows"; Platform = "windows-x86-64" },
    [PSCustomObject]@{ Name = "arm64-windows"; Platform = "windows-aarch64" }
)
$Packages = $Triplets | ForEach-Object { "libass:$($_.Name)" }
$FriBidiOverlay = Join-Path $PSScriptRoot "vcpkg-fribidi-port"
& $VcpkgExecutable install $Packages `
    "--x-install-root=$InstalledRoot" `
    "--overlay-ports=$FriBidiOverlay" `
    --clean-after-build
if ($LASTEXITCODE -ne 0) {
    throw "The pinned Windows libass build failed."
}

foreach ($Triplet in $Triplets) {
    $BinDirectory = Join-Path $InstalledRoot "$($Triplet.Name)/bin"
    $Libraries = @(
        Get-ChildItem -LiteralPath $BinDirectory -Filter "*.dll" -File |
            Sort-Object -Property Name
    )
    if ($Libraries.Count -eq 0) {
        throw "vcpkg produced no runtime DLLs for $($Triplet.Name)."
    }

    $MainLibrary = $null
    foreach ($Candidate in @("ass.dll", "ass-9.dll", "libass.dll", "libass-9.dll")) {
        $MainLibrary = $Libraries | Where-Object Name -eq $Candidate | Select-Object -First 1
        if ($null -ne $MainLibrary) {
            break
        }
    }
    if ($null -eq $MainLibrary) {
        throw "Could not identify the libass DLL for $($Triplet.Name): $($Libraries.Name -join ', ')."
    }

    $PlatformDirectory = Join-Path $ResolvedOutputRoot "composemediaplayer/ass/native/$($Triplet.Platform)"
    New-Item -ItemType Directory -Force -Path $PlatformDirectory | Out-Null
    Get-ChildItem -LiteralPath $PlatformDirectory -File |
        Where-Object { $_.Name -eq "runtime.properties" -or $_.Extension -eq ".dll" } |
        Remove-Item -Force

    foreach ($Library in $Libraries) {
        Copy-Item -LiteralPath $Library.FullName -Destination (Join-Path $PlatformDirectory $Library.Name)
    }

    $ManifestLines = [Collections.Generic.List[string]]::new()
    $ManifestLines.Add("# Generated by native/desktop/build-windows.ps1 from pinned vcpkg $VcpkgCommit.")
    $ManifestLines.Add("version=$LibAssVersion")
    $ManifestLines.Add("mainLibrary=$($MainLibrary.Name)")
    $ManifestLines.Add("file.count=$($Libraries.Count)")
    for ($Index = 0; $Index -lt $Libraries.Count; $Index++) {
        $Library = $Libraries[$Index]
        $Digest = (Get-FileHash -Algorithm SHA256 -LiteralPath $Library.FullName).Hash.ToLowerInvariant()
        $ManifestLines.Add("file.$Index.name=$($Library.Name)")
        $ManifestLines.Add("file.$Index.sha256=$Digest")
    }
    [IO.File]::WriteAllLines(
        (Join-Path $PlatformDirectory "runtime.properties"),
        $ManifestLines,
        [Text.UTF8Encoding]::new($false)
    )
}

$LicenseRoot = Join-Path $ResolvedOutputRoot "META-INF/kmediaplayer/desktop-ass/LICENSES/vcpkg"
New-Item -ItemType Directory -Force -Path $LicenseRoot | Out-Null
$CopyrightFiles = @(
    Get-ChildItem -LiteralPath (Join-Path $InstalledRoot "x64-windows/share") -Filter "copyright" -File -Recurse
)
foreach ($Copyright in $CopyrightFiles) {
    $Port = Split-Path -Leaf (Split-Path -Parent $Copyright.FullName)
    Copy-Item -LiteralPath $Copyright.FullName -Destination (Join-Path $LicenseRoot "$Port.txt") -Force
}

Write-Host "Bundled Windows libass runtimes were written to $ResolvedOutputRoot."
